### ISSUE TITLE
[gatsby-plugin-firebase] Error with SSR using netlify

### ISSUE THREAD

**Issue by jeffreymeng** [alexluong/gatsby-packages#21]
I'm using gatsby-plugin-firebase in conjunction with react-firebase-hooks, and everything works on my local dev server. However, I'm also using netlify, and all of my builds are failing after upgrading to v0.2.

I'm getting this error:
```
WebpackError: TypeError: gatsby_plugin_firebase__WEBPACK_IMPORTED_MODULE_4__.d efault.auth is not a function
```
```
12:16:45 AM: success Rewriting compilation hashes - 0.001s
12:16:46 AM: success run queries - 53.022s - 8/8 0.15/s
12:16:52 AM: [2020-03-15T07:16:52.335Z]  @firebase/app:
12:16:52 AM:       Warning: This is a browser-targeted Firebase bundle but it appears it is being
12:16:52 AM:       run in a Node environment.  If running in a Node environment, make sure you
12:16:52 AM:       are using the bundle specified by the "main" field in package.json.
12:16:52 AM:       If you are using Webpack, you can specify "main" as the first item in
12:16:52 AM:       "resolve.mainFields":
12:16:52 AM:       https://webpack.js.org/configuration/resolve/#resolvemainfields
12:16:52 AM:       If using Rollup, use the rollup-plugin-node-resolve plugin and specify "main"
12:16:52 AM:       as the first item in "mainFields", e.g. ['main', 'module'].
12:16:52 AM:       https://github.com/rollup/rollup-plugin-node-resolve
12:16:52 AM: failed Building static HTML for pages - 4.381s
12:16:52 AM: error Building static HTML failed for path "/404/"
12:16:52 AM:   43 |
12:16:52 AM:   44 | const AuthDropdown = (): ReactElement => {
12:16:52 AM: > 45 |   const [user, loading, error] = useAuthState(firebase.auth())
12:16:52 AM:      |                                                        ^
12:16:52 AM:   46 |
12:16:52 AM:   47 |   if (loading) {
12:16:52 AM:   48 |     return (
12:16:52 AM: 
12:16:52 AM:   WebpackError: TypeError: gatsby_plugin_firebase__WEBPACK_IMPORTED_MODULE_4__.d  efault.auth is not a function
12:16:52 AM:   
12:16:52 AM:   - Navbar.tsx:45 AuthDropdown
12:16:52 AM:     src/components/layout/Navbar.tsx:45:56
12:16:52 AM:   
12:16:52 AM: 
12:16:52 AM: not finished Generating image thumbnails - 7.111s
12:16:52 AM: Skipping functions preparation step: no functions directory set
```

**Comment by alexluong** [comment]
Do you have `import "firebase/auth"` in your `gatsby-browser.js`?

**Comment by jeffreymeng** [comment]
Yes. As I said, everything works on the dev server. It's only on netlify that the build breaks.

**Comment by alexluong** [comment]
Oh I see what's going on.

So at build step, you should not access Firebase, (especially authentication state, since you don't know if the user is authenticated or not).

> Just a tip in case you don't know, you can also run `gatsby build` locally before send to Netlify while debugging

> Another tip, here is a great article on this concept with Gatsby: https://joshwcomeau.com/react/the-perils-of-rehydration/

I think here are a few options:

1. Write your own `useAuthState` hook that accept `null` as argument
2. Make a PR to `react-firebase-hooks` to accept `null` as argument
3. Structure your code like so:

```js
function Component() {
  const [isInit, setIsInit] = React.useState(false);
  React.useEffect(() => setIsInit(true));
  if (!isInit) return null

  const [user, loading, error] = useAuthState(firebase.auth())

  if (loading) {
    ...
  }  
}
```

You can probably abstract this pattern into its own component/modify this idea and optimize for your user experience.

This is simply a *quirk* of Gatsby because of the built step, in which case you won't know anything about the user.

---

Let me know if this helps! I'd be happy to explain further and/or answer any question you may have.

**Comment by jeffreymeng** [comment]
This helped a lot, thanks.

I ended up writing my own useAuthState hook, which I posted [here](https://gist.github.com/jeffreymeng/78bd7f6b0f301fa5ef04359cd512222b) if anyone from the future is interested.
